### PR TITLE
`tf2_geometry_msgs`: Fixing covariance transformation in `doTransform<PoseWithCovarianceStamped, TransformStamped>`

### LINKED ISSUE #372: PoseWithCovarianceStamped transform doesn't transform covariance part
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04, but it doesn't really matter
- Installation type:
  - source code analysis
- Version or commit hash:
  - a4f152f67d09b50d6d6450bb00c44512e52a880c
- DDS implementation:
  - N/A
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```

```

#### Expected behavior
doTransform on PoseWithCovarianceStamped should also transform covariance.
#### Actual behavior
doTransform on PoseWithCovarianceStamped copies covariance without transforming it.

#### Additional information
The culprit seems to be line https://github.com/ros2/geometry2/blob/d65b7eb996dcc81bfd3389153b25b9d56eed0e8c/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L309

It seems that this functionality is implemented in ROS1 version https://github.com/ros/geometry2/blob/c73b5939723db078c9bbe18523230ad54f859682/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L927

### PR DESCRIPTION
**Pull request by aprotyas**
Previously, the covariance matrix of a `PoseWithCovarianceStamped` message [was incorrectly transformed](https://github.com/ros2/geometry2/blob/d65b7eb996dcc81bfd3389153b25b9d56eed0e8c/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L309). This PR:

- Adds a `transformCovariance` method to address the covariance transformation.
- Updates the `TfGeometry/FrameWithCovariance` unit test to check for the expected transformed covariance.

Fixes #372

### CODE REVIEW

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 1]
```diff
@@ -347,6 +349,104 @@ template <>
...
+     *
+     * Reference:
+     * 	A. L. Garcia, “Linear Transformations of Random Vectors,” in Probability,
+     * 	Statistics, and Random Processes For Electrical Engineering, 3rd ed.,
+     * 	Pearson Prentice Hall, 2008, pp. 320–322.
+     */
+
+    // get rotation matrix (and transpose)
+    tf2::Transform tf_transform;
+    fromMsg(transform, tf_transform);
```
Comment (sloretz) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Say someone already has a transform as type `tf2::Transform`, and they want to use `transformCovariance()`. They would need to convert it to `geometry_msgs::msg::Transform`, but then this function would internally convert it back. Both of those conversion steps would have been unnecessary.

Since the function operates on the `tf2::Transform` type, I would recommend making that the type of the argument. The caller's can handle transforming it from whatever datatype they have.

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 2]
```diff
@@ -347,6 +349,104 @@ template <>
...
+ * \return The transformed covariance matrix.
+ */
+inline
+geometry_msgs::msg::PoseWithCovariance::_covariance_type transformCovariance(const geometry_msgs::msg::PoseWithCovariance::_covariance_type& cov_in, const geometry_msgs::msg::Transform& transform)
+{
+    /**
+     * To transform a covariance matrix:
+     * 
+     * \verbatim[R 0] COVARIANCE [R' 0 ]
+      [0 R]            [0  R']\endverbatim
```
Comment (sloretz) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp:366]: I've never used the `\verbatim` command before. How does it look when the documentation is generated?

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 3]
```diff
@@ -347,6 +349,104 @@ template <>
...
+// Forward declaration
+void fromMsg(const geometry_msgs::msg::Transform& in, tf2::Transform& out);
+
+/** \brief Transform the covariance matrix of a PoseWithCovariance message to a new frame.
+ * \param cov_in The covariance matrix to transform.
+ * \param transform The transform to apply, as a Transform message.
+ * \return The transformed covariance matrix.
+ */
+inline
+geometry_msgs::msg::PoseWithCovariance::_covariance_type transformCovariance(const geometry_msgs::msg::PoseWithCovariance::_covariance_type& cov_in, const geometry_msgs::msg::Transform& transform)
```
Comment (sloretz) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: It looks like this file isn't being linted, but I'd still recommend [limiting the line length to 100 characters](https://docs.ros.org/en/rolling/Contributing/Code-Style-Language-Versions.html#line-length) for readability.

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 4]
```diff
@@ -347,6 +349,104 @@ template <>
...
+			         cov_in[15], cov_in[16], cov_in[17]);
+    const tf2::Matrix3x3 cov_21(cov_in[18], cov_in[19], cov_in[20],
+			         cov_in[24], cov_in[25], cov_in[26],
+			         cov_in[30], cov_in[31], cov_in[32]);
+    const tf2::Matrix3x3 cov_22(cov_in[21], cov_in[22], cov_in[23],
+			         cov_in[27], cov_in[28], cov_in[29],
+			         cov_in[33], cov_in[34], cov_in[35]);
+
+    // perform blockwise matrix multiplication
+    const tf2::Matrix3x3 result_11 = R * cov_11 * R.transpose();
```
Comment (sloretz) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: `R.transpose()` returns [a new `Matrix3x3` instance](https://github.com/ros2/geometry2/blob/6fa2001c026ff104b890663b52f2e3d518140146/tf2/include/tf2/LinearMath/Matrix3x3.h#L557-L558), so it may be more efficient to store it in a local variable instead of calling `R.transpose()` multiple times.

This comment is premature optimization so feel free to ignore.

**Review by sloretz — COMMENTED** [review]
The math LGTM (I only checked that it matches [the ROS 1 code](https://github.com/ros/geometry2/blob/c73b5939723db078c9bbe18523230ad54f859682/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L927))

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 2 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp:366]: I can't include a picture here, but the documentation looks like:
```
[R 0] COVARIANCE [R' 0 ]
[0 R]            [0  R']
```

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 1 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: If I understand correctly, you are suggesting changing the `geometry_msgs::msg::Transform` argument to `tf2::Transform`, right? I debated doing that, but I wasn't sure what would be the more common usage. Given `tf2::Transform` is the more general "transform", and not just a message type, I think I will change that argument type.

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 3 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: This is what `ament_uncrustify` recommends as well, so I will do this.

```suggestion
geometry_msgs::msg::PoseWithCovariance::_covariance_type transformCovariance(
  const geometry_msgs::msg::PoseWithCovariance::_covariance_type & cov_in,
  const geometry_msgs::msg::Transform & transform)
```

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 5]
```diff
@@ -367,7 +467,7 @@ inline
     v_out.M.GetQuaternion(t_out.pose.pose.orientation.x, t_out.pose.pose.orientation.y, t_out.pose.pose.orientation.z, t_out.pose.pose.orientation.w);
     t_out.header.stamp = transform.header.stamp;
     t_out.header.frame_id = transform.header.frame_id;
-    t_out.pose.covariance = t_in.pose.covariance;
+    t_out.pose.covariance = transformCovariance(t_in.pose.covariance, transform.transform);
```
Comment (aprotyas) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: > The caller's can handle transforming it from whatever datatype they have.

You mean something akin to this, right? @sloretz 

```suggestion
tf2::Transform tf_transform;
fromMsg(transform.transform, tf_transform);
t_out.pose.covariance = transformCovariance(t_in.pose.covariance, tf_transform);
```

Comment (sloretz) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Yup, that's what I mean!

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 1 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Addressed in 8545842360dad058

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 3 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Addressed in 8545842360dad058

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 4 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Addressed in 8545842360dad058

**Comment by aprotyas** [comment]
CI (build: `--packages-up-to tf2_geometry_msgs` test: `--packages-select tf2_geometry_msgs`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14739/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9490/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12404/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14887/)

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp [hunk 6]
```diff
@@ -347,6 +349,105 @@ template <>
...
+     */
+
+    // get rotation matrix (and transpose)
+    const tf2::Matrix3x3 R = transform.getBasis();
+    const tf2::Matrix3x3 R_transpose = R.transpose();
+
+    // convert covariance matrix into four 3x3 blocks
+    const tf2::Matrix3x3 cov_11(cov_in[0], cov_in[1], cov_in[2],
+			         cov_in[6], cov_in[7], cov_in[8],
+			         cov_in[12], cov_in[13], cov_in[14]);
```
Comment (clalancette) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: It looks like there are leading tabs in these two lines.  It is causing the function parameters to not line up (both in the GitHub UI and in `vim`).  Please convert all tabs to spaces.

The same goes several times below.

**Review by clalancette — CHANGES_REQUESTED** [review]
One minor thing to fix, then this looks good to me.

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp (hunk 6 above)
Comment (aprotyas) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp]: Done, thanks to `:retab`.

**Review by clalancette — APPROVED** [review]
Looks good to me!

**Comment by aprotyas** [comment]
@Mergifyio backport galactic foxy
