### PR TITLE
[TimeCache] Improve performance for insertData() and pruneList()

### LINKED ISSUE #676: Performance regression due to #636
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04
- Installation type: binaries
- Version or commit hash: upgrade from `0.25.3-1jammy.20230721.203549` to `0.25.6-1jammy.20240217.053651` (Debian)
- DDS implementation: `rmw_cyclonedds_cpp`
- Client library (if applicable): `rclcpp`

#### Steps to reproduce issue
This is observed performance involving sim, control, and camera publishers / subscribers.
We (@calderpg-tri and I) observed this by looking at delays for image receipt, and noticed that #636 (specifically the backport in bda8c499cc4dc3eb8ca8daccebeb10ae2e566c7d) causes an observable (significant?) delay from when an image is published to when it is received, while tf is concurrently being used.

If I use `0.25.6` but revert the given commit, I see good performance "expected behavior" in terms of timing.

~I do not yet have a minimal reproduction case.~ See benchmark in #679, and results posted below in this issue.

#### Expected behavior
Negligible performance impact

#### Actual behavior
Observable (significant?) performance impact

#### Additional information

we should consider using something more performant than `std::find()` on a `std::list`. Not immediately sure what that'll be.
From initial glance at `::insertData` and `::pruneList`, I assume `storage_` is sorted, so perhaps that can simple be changed to
```cc
bool should_insert = true;
// Search along all data with same timestamp (sorted), and only insert if we did not find the exact same data.
while (storage_it != storage_.end() && storage_it->stamp_ == new_data->stamp_) {
  if (*storage_it == new_data) {
    should_insert = false;
    break;
  }
  storage_it++;
}
if (should_insert) {
  storage_.insert(storage_it, new_data);
}
```

fyi @nachovizzo (\cc @clalancette @ahcorde)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #676

Per https://github.com/ros2/geometry2/issues/676#issuecomment-2109109282, this should yield a ~1000x speedup for `insertData` (for inserting new data only)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Hm. This is breaking `test_tf2/buffer_core_test`

EDIT: Locally, seems fixed by 898b4b3

File: tf2/src/cache.cpp [hunk 1]
```diff
@@ -255,14 +255,26 @@ bool TimeCache::insertData(const TransformStorage & new_data)
...
+  auto insertion_pos = std::find_if(
     storage_.begin(), storage_.end(), [&](const auto & transfrom) {
       return transfrom.stamp_ <= new_data.stamp_;
     });
 
+  bool should_insert = true;
+  // Search along all data with same timestamp (sorted), and only insert if we
+  // did not find the exact same data.
+  auto maybe_same_pos = insertion_pos;
+  while (maybe_same_pos != storage_.end() && maybe_same_pos->stamp_ == new_data.stamp_) {
```
Comment (nachovizzo) [inline tf2/src/cache.cpp:280]: If the benchmark says it's better, I wouldn't ever worry. But as a matter of curiosity, giving a quick look to the `std::find` implementation from GCC, how is this any different?
```
  template<typename _InputIterator, typename _Predicate>
    _GLIBCXX20_CONSTEXPR
    inline _InputIterator
    __find_if(_InputIterator __first, _InputIterator __last,
	      _Predicate __pred, input_iterator_tag)
    {
      while (__first != __last && !__pred(__first))
	      ++__first;
      return __first;
    }
```

Comment (EricCousineau-TRI) [reply tf2/src/cache.cpp:280]: The issue isn't exactly that `std::find()` itself is inefficient per se, but rather that this new code (and to some extent pre-#636 code) exploits the sorted data to reduce how much searching is done (and how expensive comparisons are overall). If you note, this code is no longer simply iterating along all elements once with a predicate, but instead it's a bit more artisanal:
- we only iterate up to the point where timestamps are equal or order
- we then only iterate along the elements that have equal timestamps, and then do full equality comparison to check if an element is already inserted (to preserve the behavior you wanted in #636).

In the best case (we immediately insert new data), we only check 1 element.
In the worst case (we insert old data at the very end, before expiration), we check all elements, but only once, and full equality is only checked for elements with exact same timestamp.

In #636, the `std::find()` introduced searches the entire `std::list` for the exact same data, using full equality comparison (very expensive).
In the best case (immediately insert new data), *all* the elements at least once, using a full equality (expensive comparison).
In the worst case (insert old data at very end, before expiration), we check all elements *twice*, once with somewhat cheap timestamp-only comparison, and once with the expensive full equality comparison.

On top of that, #658 updated `pruneData` to search *all* elements to remove al data.
This new code (and pre-#658 code) instead exploited the sorted data to only remove tail elements that are expired (which are quick O(1) operations).

So basically, #658 + #636 introduced two full searches across the data for every data point insertion, and this PR tries to accommodate the goal of #636 while still exploiting sorted structure for efficiency.

Does this make sense?

**Comment by EricCousineau-TRI** [comment]
@clalancette @ahcorde If y'all have time, would y'all also be able to review + run full CI for this PR?

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21089/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15392/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21806/)

File: tf2/src/cache.cpp [hunk 2]
```diff
@@ -255,14 +255,26 @@ bool TimeCache::insertData(const TransformStorage & new_data)
   }
 
   // Find the oldest element in the list before the incoming stamp.
-  auto last_transform_pos = std::find_if(
+  auto insertion_pos = std::find_if(
     storage_.begin(), storage_.end(), [&](const auto & transfrom) {
       return transfrom.stamp_ <= new_data.stamp_;
```
Comment (clalancette) [inline tf2/src/cache.cpp]:
```suggestion
    storage_.begin(), storage_.end(), [&](const auto & transform) {
      return transform.stamp_ <= new_data.stamp_;
```

File: tf2/src/cache.cpp (hunk 1 above)
Comment (clalancette) [reply tf2/src/cache.cpp:280]: Right, I agree with making improvements here.

For what it is worth, we are still iterating over parts (and in the worst case, all) of the list 3 times here:

1.  When we find the insertion point (which may be at the end).
2.  When we actually insert.
3.  When we prune the list.

I think it would be nice to find a way to reduce this to only one iteration over the loop, though I'm not 100% sure that is possible.  I wouldn't call this a blocker for getting this in, but since we are trying to improve the performance here I think it would make sense to go as far as we can.

@EricCousineau-TRI would you mind taking a look and seeing if we can do that?

**Review by clalancette — CHANGES_REQUESTED** [review]

File: tf2/src/cache.cpp (hunk 1 above)
Comment (EricCousineau-TRI) [reply tf2/src/cache.cpp:280]: Off the top of my head, I don't know how to easily blend the loops beyond a more intense refactoring, that I'm not 100% sure on.

That being said, we can somewhat reduce how much iteration is done by pruning first, so we don't iterate over unused data. I'll add that in.
There may be a behavior change, so we'll see if it affects downstream behavior.

Comment (EricCousineau-TRI) [reply tf2/src/cache.cpp:280]: Updated `pruneList()` 215d047e

Comment (EricCousineau-TRI) [reply tf2/src/cache.cpp:280]: Reasoning out loud:
- We now prune all old data (and should never "reconsider" it)
- We use `find_if` to scan from newest to oldest; we stop at the first point where timestamp is equal (or older)
- From this point, we scan with more expensive full equality check to ensure we have no duplicates.

I believe this should only ever scan at most N times, never more.

Does this reasoning seem sound?

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21092/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15395/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21809/)

**Review by ahcorde — APPROVED** [review]

File: tf2/src/cache.cpp [hunk 3]
```diff
@@ -250,23 +250,38 @@ bool TimeCache::insertData(const TransformStorage & new_data)
 {
   const TimePoint latest_time = getLatestTimestamp();
 
+  // Always prune data. This (a) ensures we trim data we should not access, and
+  // (b) ensures we don't waste time iterating over items to be removed.
+  pruneList();
```
Comment (clalancette) [inline tf2/src/cache.cpp:262]: I like doing this first.  It both improves performance for below, and also means that the list is always pruned, even if we are not going to insert the data.

File: tf2/src/cache.cpp (hunk 1 above)
Comment (clalancette) [reply tf2/src/cache.cpp:280]: Yep, your reasoning makes sense to me!

I'm going to suggest that we add a comment near the top of this function explaining exactly this, so that future readers (us!) will know that we thought about this.

**Review by clalancette — CHANGES_REQUESTED** [review]
This looks great; I just added a request for one more comment.  Otherwise, this will be ready to get CI run on it.

File: tf2/src/cache.cpp (hunk 1 above)
Comment (EricCousineau-TRI) [reply tf2/src/cache.cpp:280]: Done 6571fe9e

Comment (clalancette) [reply tf2/src/cache.cpp:280]: This looks great, thanks.

I'm going to run CI on it one more time.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21132/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15432/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21854/)

**Review by clalancette — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Comment by EricCousineau-TRI** [comment]
is it possible to backport this for humble (and maybe iron) as well?

**Comment by EricCousineau-TRI** [comment]
(We are very interested in having this improvement in `humble`, so please let me know if there is anything I can do to help in this respect!)

**Comment by ahcorde** [comment]
Ey @EricCousineau-TRI, 

I'm backporting some of your last PRs, if CI is green should be done today, then I will create a release

**Comment by EricCousineau-TRI** [comment]
thanks! Just looking though, and I'm not sure if I saw this one (perf improvement) backported for `humble`.
Did I miss that one?

**Comment by EricCousineau-TRI** [comment]
I ask because I only see `jazzy` and `rolling` if I search with this title:
https://github.com/ros2/geometry2/pulls?q=is%3Apr+is%3Aclosed+%5BTimeCache%5D+Improve+performance+for+insertData%28%29+and+pruneList%28%29

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble iron
