### PR TITLE
Fix tf2_echo does not work with ros-args (#407)

### LINKED ISSUE #407: tf2_echo does not work with --ros-args
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - 0.13.10 
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue
Run `tf2_echo` with an additional `ros-args` parameter e.g.:
```
ros2 run tf2_ros tf_echo --ros-args -r /tf:=/bar/tf
```

#### Expected behavior
`ros-args` parameters such as remappings can be used with `tf2_echo` (as it is possible with tf2_monitor, buffer_server, static_transform_publisher).

#### Actual behavior
If additional `ros-args` parameters are provided  only the usage information is shown and program is terminated.

#### Additional information
I have had a quick look at the source code and it looks like the reason for that is that the ros-args are not removed from command line arguments here, thus the check on the number of expected arguments in [f2_echo.cpp#L67](https://github.com/ros2/geometry2/blob/a1be44fdbd8c032351ffd3ddff8467d000f4c6d7/tf2_ros/src/tf2_echo.cpp#L67) fails. To fix this one would probably only need to use `rclcpp::iinit_and_remove_ros_arguments` instead of `rclcpp::init` as in `f2_monitor`.

https://github.com/ros2/geometry2/blob/a1be44fdbd8c032351ffd3ddff8467d000f4c6d7/tf2_ros/src/tf2_echo.cpp#L64
https://github.com/ros2/geometry2/blob/a1be44fdbd8c032351ffd3ddff8467d000f4c6d7/tf2_ros/src/tf2_monitor.cpp#L267

### PR DESCRIPTION
**Pull request by PGotzmann**
Enables the usage of `--ros-args`  by removing them before parsing the other command line parameters.
Fixes #407

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

File: tf2_ros/src/tf2_echo.cpp [hunk 1]
```diff
@@ -61,10 +62,10 @@ class echoListener
 int main(int argc, char ** argv)
 {
   // Initialize ROS
-  rclcpp::init(argc, argv);
+  std::vector<std::string> args = rclcpp::init_and_remove_ros_arguments(argc, argv);
 
   // Allow 2 or 3 command line arguments
-  if (argc < 3 || argc > 4) {
+  if (args.size() < 3 || args.size() > 4) {
```
Comment (clalancette) [inline tf2_ros/src/tf2_echo.cpp]: I'll suggest refactoring this a slightly different way (since we are in here making edits anyway).  In particular, I think it would be nicer to have the following:

```
if (args.size() == 3) {
  rate_hz = 1.0;
} else if (args.size() == 4) {
  rate_hz = std::stof(args[3]);
} else {
   printf(USAGE_MESSAGE);
   return -1;
}
```

And then continue on with the rest of the code.  What do you think about that?

File: tf2_ros/src/tf2_echo.cpp [hunk 2]
```diff
@@ -94,8 +95,8 @@ int main(int argc, char ** argv)
   // Instantiate a local listener
   echoListener echoListener(clock);
 
-  std::string source_frameid = std::string(argv[1]);
-  std::string target_frameid = std::string(argv[2]);
+  std::string source_frameid = std::string(args[1]);
+  std::string target_frameid = std::string(args[2]);
```
Comment (clalancette) [inline tf2_ros/src/tf2_echo.cpp]:
```suggestion
  std::string source_frameid = args[1];
  std::string target_frameid = args[2];
```

**Review by clalancette — CHANGES_REQUESTED** [review]
Two relatively minor changes, then I think this will be good to have CI run on it.

File: tf2_ros/src/tf2_echo.cpp (hunk 1 above)
Comment (PGotzmann) [reply tf2_ros/src/tf2_echo.cpp]: Sounds reasonable to me. This is certainly the more strait forward way here.
I will update the PRs accordingly.

**Comment by PGotzmann** [comment]
> Two relatively minor changes, then I think this will be good to have CI run on it.

Updated the PR according to your feedback.
Let me know if you are happy with that now. If so i'll update the foxy backport too.

**Review by clalancette — APPROVED** [review]
I made a few changes here to make argument parsing more robust.  This looks good to me now; thanks for the contribution!  I'll run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14539/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9295/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12204/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14645/)

**Comment by clalancette** [comment]
@Mergifyio backport galactic foxy
