### PR TITLE
Change tf2_ros C to C++ headers

### LINKED ISSUE #746: Change tf2_ros C to C++ headers
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04
- Installation type:
  - Binaries
- Version or commit hash:
  - rolling
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

In #720, all `.h` files in the `tf2` package were converted to `.hpp` with deprecation warnings -- which is great!

However, this was not done consistently throughout the repo. For example, the `tf2_ros` package still is missing several `.hpp` files. This makes it pretty inconvenient to do blanket search/replaces in downstream repos that use this.

#### Expected behavior

Every header in the repo should ideally consistently have a `.hpp` counterpart now -- not just `tf2`.

#### Actual behavior

Not the case currently.

#### Additional information

N/A

### PR DESCRIPTION
**Pull request by garyservin**
## Description

Similar to https://github.com/ros2/geometry2/pull/720, this PR moves the .h files to .hpp, while keeping a message to users about the deprecated headers.

Fixes #746

### CODE REVIEW

**Comment by ahcorde** [comment]
Pulls: ros2/geometry2#805
Gist: https://gist.githubusercontent.com/ahcorde/17e1ee53652f4cd2c0fd37cd45352c5c/raw/1a757d665d704f138a588a37feffd4915b53edac/ros2.repos
BUILD args:  --packages-above-and-dependencies test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
TEST args:  --packages-above test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16486
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24290/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18374/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24889/)

**Comment by garyservin** [comment]
Should I also fix the order of the includes in this PR?

The other failing tests is because [this line](https://github.com/ros2/geometry2/pull/805/files#diff-784c4713534186ee8f320625e34fdd4601675aaa5f55272ca754b7bbdf3fb230R33) is too long. Not sure what the process is in these cases, I could rename the define to make it shorted or ignore the linting for that line?

Thanks!

**Review by ahcorde — CHANGES_REQUESTED** [review]
> Should I also fix the order of the includes in this PR?
> 
> The other failing tests is because [this line](https://github.com/ros2/geometry2/pull/805/files#diff-784c4713534186ee8f320625e34fdd4601675aaa5f55272ca754b7bbdf3fb230R33) is too long. Not sure what the process is in these cases, I could rename the define to make it shorted or ignore the linting for that line?
> 
> Thanks!

Yes, reorder the includes according with cpplint

File: tf2_ros/include/tf2_ros/static_transform_broadcaster_visibility_control.h [hunk 1]
```diff
@@ -30,35 +30,14 @@
...
-    #define STATIC_TRANSFORM_BROADCASTER_IMPORT __declspec(dllimport)
-  #endif
-  #ifdef STATIC_TRANSFORM_BROADCASTER_BUILDING_DLL
-    #define STATIC_TRANSFORM_BROADCASTER_PUBLIC STATIC_TRANSFORM_BROADCASTER_EXPORT
-  #else
-    #define STATIC_TRANSFORM_BROADCASTER_PUBLIC STATIC_TRANSFORM_BROADCASTER_IMPORT
-  #endif
-  #define STATIC_TRANSFORM_BROADCASTER_PUBLIC_TYPE STATIC_TRANSFORM_BROADCASTER_PUBLIC
-  #define STATIC_TRANSFORM_BROADCASTER_LOCAL
+#define STATIC_TRANSFORM_BROADCASTER_VISIBILITY_CONTROL_HEADER_DEPRECATION This header is obsolete, \
```
Comment (ahcorde) [inline tf2_ros/include/tf2_ros/static_transform_broadcaster_visibility_control.h]:
```
/home/jenkins-agent/workspace/ci_linux/ws/src/garyservin/geometry2/tf2_ros/include/tf2_ros/static_transform_broadcaster_visibility_control.h:33:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
```

**Review by ahcorde — CHANGES_REQUESTED** [review]
I can here some more deprecation warnings too https://ci.ros2.org/job/ci_linux/24290/clang-tidy/

File: tf2_ros/include/tf2_ros/static_transform_broadcaster_visibility_control.h (hunk 1 above)
Comment (garyservin) [reply tf2_ros/include/tf2_ros/static_transform_broadcaster_visibility_control.h]: OK, I asked about this in my previous message as well. I renamed the define to make it a bit shorter

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24319/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18386/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3769/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24901/)

**Comment by ahcorde** [comment]
Related PRs
 - https://github.com/ros/robot_state_publisher/pull/235
 - https://github.com/ros-perception/image_pipeline/pull/1110
 - https://github.com/ros2/rviz/pull/1529

**Comment by ahcorde** [comment]
Pulls: ros2/geometry2#805, ros/robot_state_publisher#235, ros2/rviz#1529
Gist: https://gist.githubusercontent.com/ahcorde/fa4b25236bdc5813555fdcc87cf64953/raw/07ef33e1747e6de473d68d43300776fd32de3305/ros2.repos
BUILD args:  --packages-above-and-dependencies test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
TEST args:  --packages-above test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16514
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24355/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18410/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3789/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24917/)

**Comment by ahcorde** [comment]
Pulls: ros2/geometry2#805, ros/robot_state_publisher#235, ros2/rviz#1529
Gist: https://gist.githubusercontent.com/ahcorde/0d6bdc46ee2dbe5ca020f149e2cfac5f/raw/07ef33e1747e6de473d68d43300776fd32de3305/ros2.repos
BUILD args:  --packages-above-and-dependencies test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
TEST args:  --packages-above test_tf2 tf2_bullet tf2_eigen tf2_geometry_msgs tf2_kdl tf2_ros tf2_sensor_msgs
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16518
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24359/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18420/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3793/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24921/)

**Comment by Timple** [comment]
Will this also be backported without the deprecation message?

Such that packages don't have to do the whole " if ROS_DISTRO" cmake logic it they support multiple distros on a single branch?

**Comment by ahcorde** [comment]
@Timple we have done this in the past for other packages, happy to review the PR

**Comment by garyservin** [comment]
Thanks for merging @ahcorde ! One question, would it make sense to backport these changes to jazzy and kilted as well?

**Comment by ahcorde** [comment]
> Thanks for merging @ahcorde ! One question, would it make sense to backport these changes to jazzy and kilted as well?

As @Timple mentioned, we can backport these changes without the deprecation

**Comment by Timple** [comment]
Seems like @garyservin already did the honors:
https://github.com/ros2/geometry2/pull/807
