### PR TITLE
Remove template specialization for toMsg functions

### LINKED ISSUE #176: tf2_geometry_msgs geometry_msgs to TF2 StampedTransform
## Bug report

**Required Info:**

- Operating System: Ubuntu 18.04
  - 
- Installation type: Dashing latest release, E master on hash below
  - 
- Version or commit hash: 4e519f3e77611a18f03398b6334e9cc8ccf49552
  - 
- DDS implementation: Fast RTPS
  - 
- Client library (if applicable): rclcpp
  - 

#### Steps to reproduce issue

try to call

```
geometry_msgs::msg::TransformStamped toMsg(const tf2::Stamped<tf2::Transform>& in)
```
Defined here: https://github.com/ros2/geometry2/blob/ros2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L513

#### Expected behavior

I'm trying to convert a bunch of types around, and I've noticed a weird issue where all my other conversions work fine, except for this one. I get errors stating that this particular overload of `toMsg` doesnt exist. It works when I get out only a Transform, but not a stamped transform. I attempted both on Dashing from debians and on my ros2 master build, either recognize this and given it was written awhile ago I'm a bit confused why its not working.

#### Actual behavior
Typical compiler error saying it can't be found.  

```
/home/s.macenski/Documents/slam_ws/src/slam_toolbox/src/slam_toolbox_common.cpp: In member function ‘tf2::Stamped<tf2::Transform> slam_toolbox::SlamToolbox::setTransformFromPoses(const karto::Pose2&, const karto::Pose2&, const rclcpp::Time&, const bool&)’:
/home/s.macenski/Documents/slam_ws/src/slam_toolbox/src/slam_toolbox_common.cpp:398:45: error: no match for ‘operator=’ (operand types are ‘geometry_msgs::msg::TransformStamped {aka geometry_msgs::msg::TransformStamped_<std::allocator<void> >}’ and ‘geometry_msgs::msg::Transform {aka geometry_msgs::msg::Transform_<std::allocator<void> >}’)
     base_to_map_msg = tf2::toMsg(base_to_map);
```

#### Additional information

Specific set of code, while migrating Slam Toolbox to ROS2. Its ROS1 counterpart using `tf2::convert` while uses these methods under the hood has no issues. 
```
  // Compute the map->odom transform
  tf2::Stamped<tf2::Transform> odom_to_map;
  tf2::Quaternion q(0.,0.,0.,1.0);
  q.setRPY(0., 0., corrected_pose.GetHeading());
  tf2::Stamped<tf2::Transform> base_to_map(
    tf2::Transform(q, tf2::Vector3(corrected_pose.GetX(),
    corrected_pose.GetY(), 0.0)).inverse(), tf2_ros::fromMsg(t), base_frame_);
  try
  {
    geometry_msgs::msg::TransformStamped base_to_map_msg, odom_to_map_msg;
    base_to_map_msg = tf2::toMsg(base_to_map); // this fails

    // this stuff works, obviously
    // base_to_map_msg.header.stamp = tf2_ros::toMsg(base_to_map.stamp_);
    // base_to_map_msg.header.frame_id = base_to_map.frame_id_;
    // base_to_map_msg.transform.translation.x = base_to_map.getOrigin().getX();
    // base_to_map_msg.transform.translation.y = base_to_map.getOrigin().getY();
    // base_to_map_msg.transform.translation.z = base_to_map.getOrigin().getZ();
    // base_to_map_msg.transform.rotation = tf2::toMsg(base_to_map.getRotation());

    odom_to_map_msg = tf_->transform(base_to_map_msg, odom_frame_);
    tf2::fromMsg(odom_to_map_msg, odom_to_map);
  }
  catch(tf2::TransformException & e)
  {
    RCLCPP_ERROR(get_logger(), "Transform from base_link to odom failed: %s",
      e.what());
    odom_to_map.setIdentity();
  }
```

And its counterpart, fromMsg, works fine between `tf2::stamped<tf2::transform>` and `geometry_msgs/transformstamped`

### PR DESCRIPTION
**Pull request by jacobperron**
Resolves #176 

Before, the compiler was preferring the overloaded function:

https://github.com/ros2/geometry2/blob/71b054249cda9f1bbdbdc2f61bd518b998ce0378/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L397-L398

instead of the template specialization. I tried to change the overload into a template specialization, but then we run into the error that the compile can't deduce the second template parameter (ie. the return type).

I'm not sure if this is an ideal fix, or if instead we should go with template specialization (I'm not sure how we were/are benefiting from this), which requires the user to be explicit:

```c++
auto msg = tf2::toMsg<tf2::Stamped<tf2::Transform>, geometry_msgs::msg::TransformStamped>(tf_stamped);
```

I've also went ahead and made the change for stamped quaternions, which have the same bug.

### CODE REVIEW

**Comment by jacobperron** [comment]
Testing packages that depend on `tf2_geometry_msgs`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8322/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4264/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6785/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8222/)

File: tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h [hunk 1]
```diff
@@ -354,7 +354,6 @@ void fromMsg(const geometry_msgs::msg::QuaternionStamped& msg, geometry_msgs::ms
  * \param in A instance of the tf2::Quaternion specialization of the tf2::Stamped template.
  * \return The QuaternionStamped converted to a geometry_msgs QuaternionStamped message type.
  */
-template <>
 inline
 geometry_msgs::msg::QuaternionStamped toMsg(const tf2::Stamped<tf2::Quaternion>& in)
```
Comment (sloretz) [inline tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:358]: Template specialization allows different return types for the same argument (though the template arguments must be given). I don't think these two could be in the same header as overloads, and maybe not even the same binary if the compiler ignores `inline`.

```c++
geometry::msgs::Quaternion toMsg(const tf2::Stamped<tf2::Quaternion>&);
geometry::msgs::QuaternionStamped toMsg(const tf2::Stamped<tf2::Quaternion>&)
```

That said, I didn't find anyone defining `QuaternionStamped` -> `Quaternion`.

Comment (jacobperron) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:358]: I would argue that the definition

```c++
geometry::msgs::Quaternion toMsg(const tf2::Stamped<tf2::Quaternion>&);
```

shouldn't be allowed since there's a loss of information, but perhaps there's valid use-cases for this.

IIUC, if we want to keep the template specialization, for this case to work with `tf2::convert` we should update [this line](https://github.com/ros2/geometry2/blob/71b054249cda9f1bbdbdc2f61bd518b998ce0378/tf2/include/tf2/impl/convert.h#L65) to:

```diff
-  b = toMsg(a);
+  b = toMsg<A, B>(a);
```

Comment (sloretz) [reply tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:358]: > I would argue that the definition shouldn't be allowed since there's a loss of information

Maybe so. I'm not sure what the motivation for template specialization is, but it seems like that my example is not a supported use case. If `class Q Stamped` converts to either `msg Q Stamped` or `msg Q`, and `msg Q Stamped` can be converted to `class Q Stamped`, then there would be a path to convert `msg Q Stamped` to `msg Q` via `msg Q Stamped -(fromMsg)> class Q Stamped -(toMsg)> msg Q`, but message to message conversions are forbidden by this comment.

https://github.com/ros2/geometry2/blob/71b054249cda9f1bbdbdc2f61bd518b998ce0378/tf2/include/tf2/impl/convert.h#L43-L45

**Review by sloretz — APPROVED** [review]
LGTM with a recommendation to remove the templated declarations of `toMsg()` and `fromMsg()` in `tf2/convert.h` since they're no longer being used here.

I'm not sure if this can be backported. If a compiler chooses to ignore `inline`, I think the mangled name on the functions is changed when these become overloads instead of specializations.

**Comment by jacobperron** [comment]
@tfoote Before I merge this, maybe you can shed some light on if template specialization is required or if switching to overloads is fine.

**Comment by jacobperron** [comment]
@sloretz I think you're right that this is not eligible for backport, but users can still workaround the issue by explicitly providing template arguments.

I've rebased to get the latest changes and I've removed the last occurrence of the template specialization for `fromMsg` in `tf2_geometry_msgs` (499afbd). I've also updated the tests to use `tf2::convert` now that it is available (143e90d). PTAL

**Comment by jacobperron** [comment]
> recommendation to remove the templated declarations of toMsg() and fromMsg() in tf2/convert.h since they're no longer being used here.

Since the templated declarations may be used elsewhere (outside of this repo), it might be better to leave them for now.

**Comment by jacobperron** [comment]
Rerunning after the rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8467/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4358/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6880/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8368/)

**Comment by nuclearsandwich** [comment]
@jacobperron removed this from backport consideration since it is not ABI compatible.
