### PR TITLE
Fix a TOCTTOU race in tf2.

### LINKED ISSUE #305: test_tf2.MessageFilter.concurrentTransforms test is flaky on arm64
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Source
- Version or commit hash:
  - 52268361184ebf121f4a5df511805b6801ae5c64
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Recent builds exhibiting the failure

* [nightly_linux-aarch64_debug #1277](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1277/testReport/junit/test_tf2/MessageFilter/concurrentTransforms/)
* [nightly_linux-aarch64_debug #1280](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1280/testReport/junit/test_tf2/MessageFilter/concurrentTransforms/)
* [nightly_linux-aarch64_debug #1291](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1291/testReport/junit/test_tf2/MessageFilter/concurrentTransforms/)
* [nightly_linux-aarch64_debug #1306](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1306/testReport/junit/test_tf2/MessageFilter/concurrentTransforms/)

It's also failing in the repeated jobs: [nightly_linux-aarch64_repeated #1288](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/1288/)

Each failure has the same message:
```
/home/jenkins-agent/workspace/nightly_linux-aarch64_debug/ws/src/ros2/geometry2/test_tf2/test/test_message_filter.cpp:225
Expected equality of these values:
  messages
    Which is: 30
  n.count_
    Which is: 29
```

which is from this test: https://github.com/ros2/geometry2/blob/ros2/test_tf2/test/test_message_filter.cpp#L191-L229

#### Additional information

This test does not appear in the repeated job failures for any other platform or architecture.

### PR DESCRIPTION
**Pull request by clalancette**
The comment in the code has a lot more information about the
race.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Before: [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6942/)
After: [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6944/)

This fixes #305

### CODE REVIEW

File: tf2/src/buffer_core.cpp [hunk 1]
```diff
@@ -1283,6 +1283,23 @@ TransformableRequestHandle BufferCore::addTransformableRequest(
...
+  // T2: in testTransformableRequests already, holding the lock
+  // T1: blocked getting lock
+  // T2: calls all callbacks for outstanding transforms (doesn't include the current one)
+  // T2: unlocks
+  // T1: gets lock, adds to list
+  //
+  // If nothing ever calls setTransform() again, then the callback for the
+  // current request will never get called.  We fix this by holding the mutex
+  // across the entirety of this call.
+  std::unique_lock<std::mutex> lock(transformable_requests_mutex_);
```
Comment (dirk-thomas) [inline tf2/src/buffer_core.cpp:1307]: It should be possible to move the lock a bit down within the function. The first condition/return should be obvious to skip but I would think it could even go down as far as https://github.com/ros2/geometry2/pull/307/files#diff-23f1780342d49d752e5fabba0fa7de1cR1327

Comment (clalancette) [reply tf2/src/buffer_core.cpp:1307]: Yeah, totally agreed with you about moving it after the `if (target_frame == source_frame)` ; that should make it cheaper in a probably-common case.  I'll do that.

But I don't think I can move it below the check for `canTransformInternal`.  That's exactly the race; if `canTransformInternal` returns false, then we've already decided it needs to be added to the callback list.  If `testTransformableRequests` has the lock and is executing at that time, then the callback won't yet be on the list, so it won't get called there.  Since we've determined it isn't an "immediate" case the callback won't get called in `addTransformableRequest` either.  So we'll have essentially lost the event.

Comment (dirk-thomas) [reply tf2/src/buffer_core.cpp:1307]: Not sure how frequent this is being called. An alternative would be to check `canTransformInternal` without locking the mutex to allow for the early exit. And afterwards while holding the lock check `canTransformInternal` again to ensure to avoid the TOCTTOU. Just a thought though.

**Review by dirk-thomas — APPROVED** [review]

**Comment by clalancette** [comment]
Full CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6954/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9705/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11846/)

**Comment by dirk-thomas** [comment]
> Linux-aarch64

This build seems to still fail the test as reported in the supposed-to-be-fixed ticket.

**Comment by clalancette** [comment]
> This build seems to still fail the test as reported in the supposed-to-be-fixed ticket.

That's because I forgot to setup CI to use this branch.  D'oh.  Re-running.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11919/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6964/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9712/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11854/)

File: tf2/src/buffer_core.cpp (hunk 1 above)
Comment (clalancette) [reply tf2/src/buffer_core.cpp:1307]: I think that calling `canTransformInternal` twice is going to be more expensive than taking a lock.  For now, I'm going to leave this code as-is; if this turns out to be expensive later on, we can revisit the architecture and see if we can make it faster.

**Comment by clalancette** [comment]
Thanks for the review.  With the correct CI run, this is now green, so I'm going to merge.
