### PR TITLE
Default initialize TransformStorage's frame_id_ and child_frame_id_ with UINT32_MAX

### LINKED ISSUE #771: operator== Comparison Logic Issue in TransformStorage
# Bug Report
## Environment
OS Version: Ubuntu 24.04
geometry2 version: ros2 jazzy
Compiler name and version number: Ubuntu clang version 18.1.3
Source or binary build?
source build
build options: --mixin asan-gcc

## Description
In the TransformStorage class, the operator== is used to compare the member variables of two TransformStorage objects. However, the current implementation does not account for cases where some members (e.g., frame_id_) may be in an uninitialized or default-constructed state. This can lead to incorrect comparison results. Specifically, when a member variable has a default-constructed value, it is mistakenly considered equal, causing the comparison to yield unexpected results.

## Steps to reproduce
```cpp
#include <gtest/gtest.h>
#include "tf2/LinearMath/Quaternion.hpp"
#include "tf2/LinearMath/Vector3.hpp"
#include "tf2/time.hpp"
#include "tf2/transform_storage.hpp"

class TransformStorageTest : public ::testing::Test
{
protected:
  tf2::TransformStorage createTransformStorage()
  {
    const tf2::CompactFrameID frame_id(0);
    const tf2::CompactFrameID child_frame_id(1);
    const tf2::TimePoint stamp(tf2::TimePointZero);
    const tf2::Quaternion rotation(0.0, 0.0, 0.0, 1.0);
    const tf2::Vector3 translation(0.0, 0.0, 0.0);
    return tf2::TransformStorage(stamp, rotation, translation, frame_id, child_frame_id);
  }
};

TEST_F(TransformStorageTest, InvalidComparison_UninitializedMemberImpact) {
  tf2::TransformStorage t1 = createTransformStorage();
  tf2::TransformStorage t2 = t1;
  t2.frame_id_ = tf2::CompactFrameID();  // potential uninitialized/invalid value
  ASSERT_FALSE(t1 == t2);
}

```
## Output
```markdown
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TransformStorageTest
[ RUN      ] TransformStorageTest.InvalidComparison_UninitializedMemberImpact
/home/shangzh/geometry2_ws/geometry2/tf2/test/test_storage.cpp:25: Failure
Value of: t1 == t2
  Actual: true
Expected: false

[  FAILED  ] TransformStorageTest.InvalidComparison_UninitializedMemberImpact (0 ms)
[----------] 1 test from TransformStorageTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TransformStorageTest.InvalidComparison_UninitializedMemberImpact

 1 FAILED TEST
```

### PR DESCRIPTION
**Pull request by andschi**
Closes #771

### CODE REVIEW

File: tf2/test/test_storage.cpp [hunk 1]
```diff
@@ -119,12 +123,16 @@ TEST_F(TransformStorageTest, InequalityOperator) {
...
     transformStorage2.frame_id_ = 55;
     ASSERT_TRUE(transformStorage1 != transformStorage2);
+    transformStorage2.frame_id_ = tf2::CompactFrameID();
+    ASSERT_TRUE(transformStorage1 != transformStorage2);
   }
   // CompactFrameID child_frame_id_;
   {
     tf2::TransformStorage transformStorage2 = createTransformStorage();
     ASSERT_TRUE(transformStorage1 == transformStorage2);
-    transformStorage2.translation_.setValue(1.0, 0.0, 0.0);
```
Comment (andschi) [inline tf2/test/test_storage.cpp]: Looks like the test was never done with `child_frame_id_`. Instead, `translation_` was tested twice.

File: tf2/test/test_storage.cpp [hunk 2]
```diff
@@ -38,8 +38,8 @@ class TransformStorageTest : public ::testing::Test
 protected:
   tf2::TransformStorage createTransformStorage()
   {
-    const tf2::CompactFrameID frame_id(0);
-    const tf2::CompactFrameID child_frame_id(1);
+    const tf2::CompactFrameID frame_id(1);
+    const tf2::CompactFrameID child_frame_id(2);
```
Comment (andschi) [inline tf2/test/test_storage.cpp]: Initialize with valid `CompactFrameID`s.

File: tf2/include/tf2/transform_storage.hpp [hunk 3]
```diff
@@ -56,6 +56,13 @@ class TransformStorage
     *this = rhs;
   }
 
+  TF2_PUBLIC
+  bool isValid() const
+  {
+    return (frame_id_ != 0) &&
+           (child_frame_id_ != 0); 
+  }
```
Comment (andschi) [inline tf2/include/tf2/transform_storage.hpp]: Happy to move this to the `operator==()` if we do not want this extra member function.

**Review by kscottz — APPROVED** [review]
LGTM. Thanks for the help.

**Review by fujitatomoya — COMMENTED** [review]
please hold this PR until https://github.com/ros2/geometry2/issues/771#issuecomment-2831343452 is answered.

btw, our development branch is `rolling`, and then we can backport the fix to released branches.

**Comment by andschi** [comment]
> btw, our development branch is rolling, and then we can backport the fix to released branches.

@fujitatomoya , got it. I set this PR's base branch to rolling and rebased.

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
Pulls: ros2/geometry2#783
Gist: https://gist.githubusercontent.com/fujitatomoya/670e1dba0e4595852ce453f128dde7f1/raw/0b27886ea86292cf1594bd8ebbf02003444d43d2/ros2.repos
BUILD args:  --packages-above-and-dependencies tf2
TEST args:  --packages-above tf2
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16215
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23956/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18013/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3357/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24604/)

**Comment by andschi** [comment]
All green! Let‘s merge away and close the issue, @fujitatomoya ?
