### PR TITLE
 Fix race between timeout and transform ready callback

### LINKED ISSUE #141: Raise std::future_error: Promise already satisfied
## Bug report

**Required Info:**

- Operating System:
Ubuntu 18.04
- Installation type:
source
- Version or commit hash:
e29db0a46edfd1ccfbf538096ad605359f7a6109
- DDS implementation:
Fast-RTPS
- Client library (if applicable):
rclcpp, nav2_amcl

#### Steps to reproduce issue
Launching nav2_bringup's nav2_simulation_launch.py and waiting some minutes.

#### Expected behavior
Nothing happen

#### Actual behavior
Exception(`what():  std::future_error: Promise already satisfied`) is raised at the following code.
https://github.com/ros2/geometry2/blob/e29db0a46edfd1ccfbf538096ad605359f7a6109/tf2_ros/src/buffer.cpp#L256

#### Additional information
It seems `Buffer::timerCallback` is called
https://github.com/ros2/geometry2/blob/e29db0a46edfd1ccfbf538096ad605359f7a6109/tf2_ros/src/buffer.cpp#L256
after `cb_handle` is called.
https://github.com/ros2/geometry2/blob/e29db0a46edfd1ccfbf538096ad605359f7a6109/tf2_ros/src/buffer.cpp#L205

### PR DESCRIPTION
**Pull request by jacobperron**
The timer-request handle map is used to check if the promise to the user has already been set.
For the transformable request callback, we loop over the values of the map to check if the request is still valid.
Alternatively, we could implement a bi-directional map for efficiency, but I don't expect the number of entries in the timer-request map to be large so it seems like a pre-mature optimization.

Fixes #141

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7802/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3878/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6367/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7634/)

**Review by wjwwood — APPROVED** [review]

File: tf2_ros/src/buffer.cpp [hunk 1]
```diff
@@ -246,17 +265,25 @@ Buffer::timerCallback(const TimerHandle & timer_handle,
...
+    timer_is_valid = (timer_to_request_map_.end() != timer_and_request_it);
+    if (timer_is_valid) {
+      request_handle = timer_and_request_it->second;
+    }
     timer_to_request_map_.erase(timer_handle);
+    timer_interface_->remove(timer_handle);
+  }
+
+  if (timer_is_valid) {
+    cancelTransformableRequest(request_handle);
```
Comment (dirk-thomas) [inline tf2_ros/src/buffer.cpp:282]: This line introduced a compiler warning: https://ci.ros2.org/view/packaging/job/packaging_linux/1559/warnings23Result/new/

@jacobperron Please address this.

Comment (jacobperron) [reply tf2_ros/src/buffer.cpp:282]: See #148
